/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexQuery.graphql
 * @generated SignedSource<<85d1e3f0acbee9eadf77e2302826d964>>
 * @relayHash 1df5a3ca17e98f1771601d9fd2faa319
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexQuery {
  viewer {
    ...Users_viewer
  }
}

fragment Users_viewer on Viewer {
  users(type: admin) {
    ...UserList_users
  }
}

fragment UserList_users on User {
  id
  ...UserItem_user
}

fragment UserItem_user on User {
  id
  firstName
  lastName
  email
  isActive
  roles {
    id
    title
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Users_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "indexQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "type",
                "value": "admin",
                "type": "Site!"
              }
            ],
            "concreteType": "User",
            "name": "users",
            "plural": true,
            "selections": [
              {
                "kind": "InlineFragment",
                "type": "User",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "firstName",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "lastName",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "email",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "isActive",
                    "storageKey": null
                  },
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "Role",
                    "name": "roles",
                    "plural": true,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "id",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "title",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": "users{\"type\":\"admin\"}"
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query indexQuery {\n  viewer {\n    ...Users_viewer\n  }\n}\n\nfragment Users_viewer on Viewer {\n  users(type: admin) {\n    ...UserList_users\n  }\n}\n\nfragment UserList_users on User {\n  id\n  ...UserItem_user\n}\n\nfragment UserItem_user on User {\n  id\n  firstName\n  lastName\n  email\n  isActive\n  roles {\n    id\n    title\n  }\n}\n"
};

module.exports = batch;
