/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Users_viewer.graphql
 * @generated SignedSource<<9e7f8f9f53aaeb82854aa40462150e04>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Users_viewer = {
  users?: ?Array<?any>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Users_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "type",
          "value": "admin",
          "type": "Site!"
        }
      ],
      "concreteType": "User",
      "name": "users",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "UserList_users",
          "args": null
        }
      ],
      "storageKey": "users{\"type\":\"admin\"}"
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
