/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserList_users.graphql
 * @generated SignedSource<<7b59f37dcacc10dc697592f2373ed570>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type UserList_users = {
  id?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "UserList_users",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "UserItem_user",
      "args": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
