/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule index.graphql
 * @generated SignedSource<<90154185873fbb5b1aaf8b0dbce69968>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type index = {
  users?: ?Array<?index_users>;
};

export type index_users = {
  id?: ?string;
  firstName?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "index",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "type",
          "value": "admin",
          "type": "Site!"
        }
      ],
      "concreteType": "User",
      "name": "users",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "firstName",
          "storageKey": null
        }
      ],
      "storageKey": "users{\"type\":\"admin\"}"
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
