/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexProductEditQuery.graphql
 * @generated SignedSource<<2b2b977c58f6d1927fa59770ffa76fee>>
 * @relayHash 873f6325327d25806eda90543524347a
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexProductEditQuery(
  $id: String!
  $shopCode: String!
) {
  viewer {
    ...ProductEdit_viewer
    products(shopCode: $shopCode, id: $id) {
      id
    }
  }
}

fragment ProductEdit_viewer on Viewer {
  products(shopCode: $shopCode, id: $id) {
    id
    sku
    name
    description
    curr
    price
    isActive
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "String!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "shopCode",
        "type": "String!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexProductEditQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "ProductEdit_viewer",
            "args": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "id",
                "variableName": "id",
                "type": "String"
              },
              {
                "kind": "Variable",
                "name": "shopCode",
                "variableName": "shopCode",
                "type": "String!"
              }
            ],
            "concreteType": "Product",
            "name": "products",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexProductEditQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "String!",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "shopCode",
        "type": "String!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "indexProductEditQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "id",
                "variableName": "id",
                "type": "String"
              },
              {
                "kind": "Variable",
                "name": "shopCode",
                "variableName": "shopCode",
                "type": "String!"
              }
            ],
            "concreteType": "Product",
            "name": "products",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "sku",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "description",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "curr",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "price",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "isActive",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query indexProductEditQuery(\n  $id: String!\n  $shopCode: String!\n) {\n  viewer {\n    ...ProductEdit_viewer\n    products(shopCode: $shopCode, id: $id) {\n      id\n    }\n  }\n}\n\nfragment ProductEdit_viewer on Viewer {\n  products(shopCode: $shopCode, id: $id) {\n    id\n    sku\n    name\n    description\n    curr\n    price\n    isActive\n  }\n}\n"
};

module.exports = batch;
