/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexProductsQuery.graphql
 * @generated SignedSource<<3e76ecc80a7d891b4f9bbc8cf1c2a843>>
 * @relayHash a8c7d524a69f8e4d564e8baf5c0e2403
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexProductsQuery(
  $shopCode: String!
) {
  viewer {
    ...Products_viewer
    products(shopCode: $shopCode) {
      id
    }
  }
}

fragment Products_viewer on Viewer {
  products(shopCode: $shopCode) {
    id
    ...ProductList_products
  }
}

fragment ProductList_products on Product {
  id
  ...ProductItem_product
}

fragment ProductItem_product on Product {
  id
  sku
  name
  description
  curr
  price
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "shopCode",
        "type": "String!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexProductsQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Products_viewer",
            "args": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "shopCode",
                "variableName": "shopCode",
                "type": "String!"
              }
            ],
            "concreteType": "Product",
            "name": "products",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexProductsQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "shopCode",
        "type": "String!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "indexProductsQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "shopCode",
                "variableName": "shopCode",
                "type": "String!"
              }
            ],
            "concreteType": "Product",
            "name": "products",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "InlineFragment",
                "type": "Product",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "sku",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "description",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "curr",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "price",
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query indexProductsQuery(\n  $shopCode: String!\n) {\n  viewer {\n    ...Products_viewer\n    products(shopCode: $shopCode) {\n      id\n    }\n  }\n}\n\nfragment Products_viewer on Viewer {\n  products(shopCode: $shopCode) {\n    id\n    ...ProductList_products\n  }\n}\n\nfragment ProductList_products on Product {\n  id\n  ...ProductItem_product\n}\n\nfragment ProductItem_product on Product {\n  id\n  sku\n  name\n  description\n  curr\n  price\n}\n"
};

module.exports = batch;
