/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Products_viewer.graphql
 * @generated SignedSource<<0dbb1807692eb0a0288b9012de25711e>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Products_viewer = {
  products?: ?Array<?Products_viewer_products>;
};

export type Products_viewer_products = {
  id?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "shopCode",
      "type": "String!"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "Products_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "shopCode",
          "variableName": "shopCode",
          "type": "String!"
        }
      ],
      "concreteType": "Product",
      "name": "products",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "FragmentSpread",
          "name": "ProductList_products",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
