/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ProductList_products.graphql
 * @generated SignedSource<<73820b5e8d9d61b991f18b7782e0fe7e>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type ProductList_products = {
  id?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "ProductList_products",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "ProductItem_product",
      "args": null
    }
  ],
  "type": "Product"
};

module.exports = fragment;
