/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UpdateProductActiveMutation.graphql
 * @generated SignedSource<<6c208fdc54d92bd873c81a2d57008926>>
 * @relayHash ec0345eec6294822ed11c8f38e00c214
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type UpdateProductActiveInput = {
  id?: ?string;
  isActive?: ?boolean;
};

export type UpdateProductActiveMutationResponse = {
  id?: ?string;
  sku?: ?string;
  name?: ?string;
  description?: ?string;
  curr?: ?string;
  price?: ?number;
  isActive?: ?boolean;
};
*/

/* eslint-disable comma-dangle, quotes */

/*
mutation UpdateProductActiveMutation(
  $input: UpdateProductActiveInput!
) {
  updateProductActive(input: $input) {
    id
    sku
    name
    description
    curr
    price
    isActive
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "UpdateProductActiveInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "UpdateProductActiveMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "UpdateProductActiveInput!"
          }
        ],
        "concreteType": "Product",
        "name": "updateProductActive",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "sku",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "description",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "curr",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "price",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "isActive",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "UpdateProductActiveMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "UpdateProductActiveInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "UpdateProductActiveMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "UpdateProductActiveInput!"
          }
        ],
        "concreteType": "Product",
        "name": "updateProductActive",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "sku",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "description",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "curr",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "price",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "isActive",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation UpdateProductActiveMutation(\n  $input: UpdateProductActiveInput!\n) {\n  updateProductActive(input: $input) {\n    id\n    sku\n    name\n    description\n    curr\n    price\n    isActive\n  }\n}\n"
};

module.exports = batch;
