/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Feed.graphql
 * @generated SignedSource<<6a1d835b4a6eca6542c51269c8f33928>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Feed = {
  users?: ?Array<?Feed_users>;
};

export type Feed_users = {
  id?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Feed",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "type",
          "value": "admin",
          "type": "Site!"
        }
      ],
      "concreteType": "User",
      "name": "users",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        }
      ],
      "storageKey": "users{\"type\":\"admin\"}"
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
