/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexUserAddQuery.graphql
 * @generated SignedSource<<d58cdee0d50da476f63a133d53eb1023>>
 * @relayHash 84152cc576972e7b70561b7092926a9e
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexUserAddQuery {
  viewer {
    ...UserAdd_viewer
  }
}

fragment UserAdd_viewer on Viewer {
  roles(type: admin) {
    id
    title
    isSuper
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexUserAddQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "UserAdd_viewer",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexUserAddQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "indexUserAddQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "type",
                "value": "admin",
                "type": "Site!"
              }
            ],
            "concreteType": "Role",
            "name": "roles",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "title",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "isSuper",
                "storageKey": null
              }
            ],
            "storageKey": "roles{\"type\":\"admin\"}"
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query indexUserAddQuery {\n  viewer {\n    ...UserAdd_viewer\n  }\n}\n\nfragment UserAdd_viewer on Viewer {\n  roles(type: admin) {\n    id\n    title\n    isSuper\n  }\n}\n"
};

module.exports = batch;
