/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserEdit_viewer.graphql
 * @generated SignedSource<<d6be1d7276a653dacd2c09baa93af47c>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type UserEdit_viewer = {
  roles?: ?Array<?UserEdit_viewer_roles>;
  users?: ?Array<?UserEdit_viewer_users>;
};

export type UserEdit_viewer_roles = {
  id?: ?string;
  title?: ?string;
  isSuper?: ?boolean;
};

export type UserEdit_viewer_users_roles = {
  id?: ?string;
  title?: ?string;
  isSuper?: ?boolean;
};

export type UserEdit_viewer_users = {
  id?: ?string;
  email?: ?string;
  firstName?: ?string;
  lastName?: ?string;
  roles?: ?Array<?UserEdit_viewer_users_roles>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "userId",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "UserEdit_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "type",
          "value": "admin",
          "type": "Site!"
        }
      ],
      "concreteType": "Role",
      "name": "roles",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "title",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "isSuper",
          "storageKey": null
        }
      ],
      "storageKey": "roles{\"type\":\"admin\"}"
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "id",
          "variableName": "userId",
          "type": "String"
        },
        {
          "kind": "Literal",
          "name": "type",
          "value": "admin",
          "type": "Site!"
        }
      ],
      "concreteType": "User",
      "name": "users",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "email",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "firstName",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "lastName",
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "Role",
          "name": "roles",
          "plural": true,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "title",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "isSuper",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
