/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UpdateUserActiveMutation.graphql
 * @generated SignedSource<<b2151f8ec0d125a591019e61b9f8158a>>
 * @relayHash 12514e391154f57fe2234152c46d6b10
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type UpdateUserActiveInput = {
  id?: ?string;
  isActive?: ?boolean;
};

export type UpdateUserActiveMutationResponse = {
  id?: ?string;
  email?: ?string;
  firstName?: ?string;
  lastName?: ?string;
  isActive?: ?boolean;
  roles?: ?Array<?UpdateUserActiveMutationResponse_roles>;
};

export type UpdateUserActiveMutationResponse_roles = {
  id?: ?string;
  title?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

/*
mutation UpdateUserActiveMutation(
  $input: UpdateUserActiveInput!
) {
  updateUserActive(input: $input) {
    id
    email
    firstName
    lastName
    isActive
    roles {
      id
      title
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "UpdateUserActiveInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "UpdateUserActiveMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "UpdateUserActiveInput!"
          }
        ],
        "concreteType": "User",
        "name": "updateUserActive",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "email",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "firstName",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lastName",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "isActive",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Role",
            "name": "roles",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "title",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "UpdateUserActiveMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "UpdateUserActiveInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "UpdateUserActiveMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "UpdateUserActiveInput!"
          }
        ],
        "concreteType": "User",
        "name": "updateUserActive",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "email",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "firstName",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lastName",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "isActive",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Role",
            "name": "roles",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "title",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation UpdateUserActiveMutation(\n  $input: UpdateUserActiveInput!\n) {\n  updateUserActive(input: $input) {\n    id\n    email\n    firstName\n    lastName\n    isActive\n    roles {\n      id\n      title\n    }\n  }\n}\n"
};

module.exports = batch;
